# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7f10593de3769741f529f7213579e76970f25f43651396b83dd8af22afd1fc1a5444fafdcd1ccbf20be83791c75997d71e3862b8f1cf2a065f9bc9c158305a5

test:
  secret_key_base: 565714c1748d00b5067dc7024403ec8df58a18a12bc087237f066b7f9e9e3d2c880654456c883874785f6595ffb4f97866c0987843b75821600181c9a954656d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
